# Sieu tham so cho mo hinh ExtraTreesClassifier
# Thay doi cac gia tri nay giua cac lan chay de thi nghiem (Buoc 1)
n_estimators: 800
max_depth: null
min_samples_split: 2
max_features: sqrt
use_phase2: true
